### PR TITLE
Section 2 minor fixes

### PR DESCRIPTION
**Pull request by jcarlosgarcia**
Fixed minor typos and errors in section 2.

### CODE REVIEW

**Review by SuzeShardlow — APPROVED** [review]
Looks good to me!  @simonprickett please merge this.

**Comment by SuzeShardlow** [comment]
@jcarlosgarcia thanks for your contribution!  I don't know if you are taking part in [Hacktoberfest](https://redis.io/community/hacktoberfest), but I've marked this as Hacktoberfest approved anyway.  If you are a member of our [Discord server](https://discord.gg/redis), feel free to let us know your handle and I will give you the Hacktoberfest role there.  If not, no worries :)

Hope you enjoyed RU204 :)

**Comment by simonprickett** [comment]
Note to self:

- [ ] Apply changes to 2022_09 course run
- [ ] Apply changes to 2022_10 course run
- [ ] Apply changes to SP course run

**Comment by jcarlosgarcia** [comment]
Thanks @SuzeShardlow . Yes, I'm jcarlosgarcia#0192 on Discord.

**Review by simonprickett — APPROVED** [review]

**Comment by simonprickett** [comment]
Thanks @jcarlosgarcia these changes are now live in the learning platform.

**Pull request merged**
